import asyncio, subprocess, sys
from pathlib import Path
sys.path.insert(0, "/data/.openclaw/tools/two-voice-tts")
import edge_tts
import imageio_ffmpeg

ROOT = Path(__file__).resolve().parent.parent
VOICE = {"host": "en-US-AvaMultilingualNeural", "guest": "en-GB-RyanNeural"}

EPISODES = {
"002": {
"title": "Can We See Learning in the Game?",
"slug": "can-we-see-learning-in-the-game",
"dialogue": [
('host', "Welcome back to Human in the Loop, the show where educational technology brings a spreadsheet to a game night and we ask what the spreadsheet actually knows. Today we're looking at game learning analytics: traces, dashboards, detectors, and the perilous moment when a number starts dressing up as a conclusion. Joining me is Doctor Rowan Field, our fictional research correspondent and composite voice for the studies in today's episode. Rowan, are you carrying a graph?"),
('guest', "Only three graphs and a pocket calculator for emotional support. And to be clear at the outset, I am fictional. I do not speak for any author, and nobody we discuss was interviewed for this episode. This is an AI-generated summary and paraphrased synthesis of the cited literature. It can contain errors, and it is an orientation, not a substitute for reading the sources. I am here to translate the research, preserve its caveats, and occasionally stop you from calling a click a learning event."),
('host', "A click is not learning. There goes my entire career as a very small button."),
('guest', "Your career may survive. The central problem is that games produce a remarkable amount of behavior data: choices, timing, revisits, attempts, pauses, conversations, and paths through a system. Those traces can help us ask better questions. They cannot answer every question by themselves."),
('host', "Let's start with the plumbing. SIMVA sounds like the sort of thing that enters wearing a tool belt."),
('guest', "Our first full citation is Julio Santilario-Berthilier, Antonio Calvo-Morata, Ivan Martinez-Ortiz, Marc Spaniol, and Baltasar Fernandez-Manjon, ‘SIMVA: Serious Games Learning Analytics Based on Standards and Open Code,’ published in the Joint Proceedings of the Learning Analytics and Knowledge 2025 Workshops, in 2025. SIMVA stands for SIMple VAlidator. The paper presents an open-source, standards-based platform for serious-game learning analytics. It uses IEEE xAPI to describe experiences, can connect with a Learning Record Store, and can work with different trackers and storage systems. The design goal is practical: reduce the cost and proprietary complexity that can make game analytics difficult to reproduce or share."),
('host', "So instead of every game inventing a private dialect of telemetry, we get a common language?"),
('guest', "A more common language, yes. Not a universal dictionary of meaning. SIMVA also supports basic analysis and visualization, experimental designs such as control groups and A/B tests, and pre- and post-questionnaires linked to gameplay through anonymized codes. That last connection matters because an interaction trace can be interpreted alongside an outcome measure rather than treated as the outcome itself."),
('host', "The phrase ‘anonymized codes’ is doing serious work there."),
('guest', "It is. Data ownership, privacy, and linkage are part of the research design. A code can reduce direct identification, but it does not magically make a dataset harmless. The paper is a platform contribution. It shows how to collect, organize, and validate evidence; it is not a guarantee that any metric generated by the platform measures learning."),
('host', "That feels like the first rule of our analytics clubhouse: make the data easier to inspect, then still inspect it."),
('guest', "Exactly. Our second source is Sergej Görzen, Birte Heinemann, and Ulrik Schroeder, ‘Evaluation of a Framework for the Integrating of Learning Analytics in Virtual Reality,’ published by Gesellschaft für Informatik in 2024. It asks a different question: can researchers and developers build analytics that are sustainable, FAIR, reproducible, reusable, and accurate? Here FAIR means that research data should be findable, accessible, interoperable, and reusable. The authors developed an ecosystem through an iterative process and observed seven computer-science students integrating learning analytics into a VR application."),
('host', "Seven people is enough for a small room, but not enough to represent humanity, or even a particularly crowded lab meeting."),
('guest', "That is the appropriate caution. The observation study examined productivity, workflow, usability, functionality, and challenges. It tells us about the work of integrating analytics. It does not establish learning gains, nor does it settle how every learner experiences a VR system. Its value is implementation evidence: if the collection pipeline is brittle, the educational claim built on it will be brittle too."),
('host', "So before asking whether a learner learned, ask whether the measurement system survived contact with reality."),
('guest', "And whether another team could understand and reuse it. FAIR principles are not decorative initials. Findability, accessibility, interoperability, and reusability shape what can be checked later. A beautiful dashboard backed by opaque, irreproducible logs is a very polished mystery."),
('host', "Now let's turn to an especially mischievous mystery: detecting teacher remediation from student-system logs."),
('guest', "The full citation is William L. Miller, Ryan S. Baker, Matthew J. Labrum, Karen Petsche, Yu-Han Liu, and Angela Z. Wagner, ‘Automated Detection of Proactive Remediation by Teachers in Reasoning Mind Classrooms,’ in the Proceedings of the Fifth International Conference on Learning Analytics and Knowledge, published by ACM in 2015. The study focuses on proactive remediation, meaning a teacher dynamically plans an intervention with one or more students. The important wrinkle is that the activity may occur outside the learning system. The authors show that interaction logs can still help infer education-related teacher-student interactions, and they present a sensor-free detector distinguishing remediation from idle time, on-task conversation related to immediate learning, and off-task behavior."),
('host', "The log sees the shadow of the teacher, not the whole teacher."),
('guest', "A useful image. Inference is not observation in the broad human sense. A detector can identify patterns associated with a construct, but context can change the meaning of the same pattern. A pause might be confusion, a thoughtful discussion, a technical failure, or someone looking for a pencil. The study demonstrates a promising signal, not a license to surveil or automatically judge."),
('host', "And if the system is used to trigger help, a false alarm may be awkward. If it is used to label a teacher or student, the stakes rise sharply."),
('guest', "Which brings us to Ryan Baker, Caitlin Mills, and Jaeyoon Choi, ‘The Difficulty of Achieving High Precision with Low Base Rates for High-Stakes Intervention,’ in the Proceedings of the Fifteenth International Learning Analytics and Knowledge Conference, published by ACM in 2025. Suppose a target behavior is uncommon. Even a detector that sounds impressive can generate many false positives because the rare cases are surrounded by many ordinary cases. Precision asks, among the cases flagged, how many really are the target. When the base rate is low, that denominator matters enormously."),
('host', "Give me the tiny-math version without making me relive algebra."),
('guest', "Imagine one hundred students and only five genuinely need a particular intervention. A detector flags ten students, including four of the five who need it. Recall looks encouraging: four out of five. But precision is four out of ten. Six students were flagged unnecessarily. If the intervention is costly, stigmatizing, or harmful, those six are not a footnote."),
('host', "And the paper says our usual metrics may not answer the decision question."),
('guest', "Right. F1, Kappa, specificity, and area under the ROC curve each have legitimate uses, but they can be insufficient when the operational requirement is high precision at a specific threshold. The lesson is not ‘never use metrics.’ It is ‘choose metrics that match the consequence and the base rate.’ Then report the confusion matrix and the actual threshold behavior."),
('host', "That sounds less glamorous than a single score, which is probably why it is better."),
('guest', "A single score is wonderfully compact and wonderfully capable of hiding the part you needed. A responsible analytics report says what was predicted, for whom, at what prevalence, with what errors, and what happened after the prediction."),
('host', "Where does knowledge tracing enter this story?"),
('guest', "Our fifth source is Philip I. Pavlik Junior, Hao Cen, and Kenneth R. Koedinger, ‘Performance Factors Analysis: A New Alternative to Knowledge Tracing,’ in the Proceedings of the Fourteenth International Conference on Artificial Intelligence in Education, published in Frontiers in Artificial Intelligence and Applications by IOS Press in 2009. Performance Factors Analysis, or PFA, is an educational-data-mining model proposed as an alternative to standard knowledge tracing. The paper describes models built around learning factors and knowledge components, with an aim to support adaptive practice. It addresses limitations the authors identify in classic knowledge tracing and learning-factor approaches, including multiple skills involved in one action and the possibility of modeling action latency."),
('host', "So the model is trying to represent a learner's changing relationship with skills, not just keep a glowing ‘knows it’ light on."),
('guest', "That is the intuition. The paper compares PFA with versions of Learning Factors Analysis and with standard knowledge tracing. Such comparisons help us understand predictive and modeling tradeoffs. They do not by themselves prove that an adaptive system improves a classroom, a learner's confidence, or a teacher's judgment. A model can be mathematically elegant and educationally misplaced."),
('host', "The phrase ‘knowledge component’ also sounds like a box we should not confuse with knowledge itself."),
('guest', "Precisely. A component is a modeling decision: a way to represent a skill, concept, or fact for a purpose. Different decompositions can produce different predictions. The model is a lens, not the learner. It may help decide what practice to offer, while a teacher and learner still need to decide whether that practice is meaningful."),
('host', "And the game-based collaborative inquiry paper gives us the social side of the trace."),
('guest', "It does. The complete citation is Asmalina Saleh, Chen Yuxin, Cindy E. Hmelo-Silver, Krista D. Glazewski, Bradford W. Mott, and James C. Lester, ‘Coordinating Scaffolds for Collaborative Inquiry in a Game-Based Learning Environment,’ in the Journal of Research in Science Teaching, 2020. The study frames collaborative science inquiry as a problem-based, game-based learning environment and identifies two functions that need scaffolding: the inquiry cycle and accountable talk. The key idea is coordination. Scaffolds have forms and functions, and supporting one activity can interfere with another if they are not designed together."),
('host', "A dashboard could tell us that a group made fewer moves, but not whether they were quietly building a better explanation together."),
('guest', "Exactly. In collaborative inquiry, language, timing, roles, and visible actions can be entangled. A trace can help identify patterns for further investigation, but interpretation should return to the activity: what was the group trying to explain, what evidence did members use, and how did the scaffold shape their conversation?"),
('host', "Let's make a field guide. If a game generates data, what should a researcher do before announcing that the game taught something?"),
('guest', "First, define the construct independently of the available log fields. Do not begin with ‘we have clicks’ and work backward to ‘therefore, engagement.’ Second, document the event schema, time windows, missingness, and linkage. Third, pair traces with outcomes that can actually bear on the claim: assessments, transfer tasks, explanations, or carefully designed observations."),
('host', "Fourth: check the denominator before celebrating the detector."),
('guest', "Yes. Fourth, examine prevalence and error costs. A detector that is acceptable for exploratory research may be unacceptable for an automated intervention. Fifth, test whether the pattern travels across learners, classes, games, and contexts. Sixth, give people a way to contest an interpretation. A learner is not a row in a table, and a teacher is not a latent variable with a coffee habit."),
('host', "That last part may be your most statistically underpowered claim."),
('guest', "I welcome replication."),
('host', "What is the hopeful version?"),
('guest', "Well-designed analytics can make learning processes more visible. Standards can support reuse. Open tools can lower barriers. Models can help target practice. Traces can reveal moments worth discussing, including forms of teacher support that would otherwise be invisible. But visibility is an invitation to inquiry, not a substitute for inquiry."),
('host', "And the memorable version?"),
('guest', "Let the log point. Let the learner explain. Let the outcome test the claim. Let the human remain accountable for the decision."),
('host', "This episode was an AI-generated summary and dramatized synthesis by a fictional correspondent. It can contain errors, it paraphrases the six sources, and it is neither an actual author interview nor a substitute for reading them. The complete citations are in the show notes, with links to the Zotero files when you have been granted access. Rowan, thank you for bringing six methods and only three graphs."),
('guest', "My pleasure. Please report the false positives, the missing data, and the humans who had to clean the spreadsheet."),
('host', "Until next time, keep the human in the loop—and the denominator in view."),
]},
"003": {
"title": "When a Game Needs a Teacher",
"slug": "when-a-game-needs-a-teacher",
"dialogue": [
('host', "Welcome back to Human in the Loop. Today we are investigating a suspicious phrase: educational game. Does the adjective do any work, or is it just wearing a little backpack? Doctor Rowan Field, our fictional research correspondent, is here to interrogate design, scaffolding, feedback, and assessment. Rowan, what makes a game teach?"),
('guest', "A relationship between the game system, the learning goal, and the player's activity. Also, I am fictional and speak only as a composite translator of the research. No author is speaking through me, nobody was interviewed, and every claim today is a paraphrase with evidence limits attached."),
('host', "Good. Now remove the backpack and explain the relationship."),
('guest', "An educational game is not automatically educational because it contains facts, points, or a cartoon wearing spectacles. The design must create meaningful opportunities to practice, notice, explain, revise, or transfer something that matters beyond the screen. Sometimes the game mechanic itself embodies the learning goal. Sometimes the game supplies a context that still needs instruction, discussion, or assessment around it."),
('host', "So a game can be fun, informative, and educationally useless all at once?"),
('guest', "It can. The question is not whether players enjoyed it. The question is what activity the design made possible and what evidence shows that activity supported learning."),
('host', "Let's begin with the shiny new guest at the design table: a generative-AI chatbot inside digital game-based science learning."),
('guest', "The study by Huang and Chen examined 160 seventh-grade students in a digital game-based learning environment. It used a two-by-two design involving instructional videos and a GenAI-supported chatbot. The researchers examined science learning, game performance, cognitive load, and game behaviors, including sequential patterns in trace data."),
('host', "Two kinds of help: one carefully prepared, one dynamically conversational."),
('guest', "Yes. Instructional videos provided systematic assistance about science concepts inside the game. The chatbot provided adaptive, contextual advice and feedback. The clearest result was that the video groups outperformed the groups without videos on science learning. The reported effect was substantial: F one comma one-five-three equals fifty-five point sixty-four, p less than point zero-zero-one, partial eta squared point two-seven."),
('host', "That is a lot of punctuation for ‘the video mattered.’"),
('guest', "The punctuation helps show that it was an inferential result, not a vibe. The combination of video and chatbot also produced the lowest extraneous cognitive load, with a reported interaction effect, while the GenAI-only group showed the most fragmented game inquiry behaviors. The authors also underscore self-regulated learning: a flexible chatbot is not automatically a good scaffold for every learner."),
('host', "The bot can be adaptive and still make the learner's inquiry less coherent."),
('guest', "Exactly. A response can be locally helpful and globally distracting. This is why a chatbot should not be evaluated only by whether its sentence sounds friendly. We need to ask whether it directs attention toward the scientific idea, preserves productive struggle, and supports a learner's next meaningful action."),
('host', "What did the study not prove?"),
('guest', "It did not prove that GenAI chatbots generally improve learning, that the same effects appear in other ages or subjects, or that a chatbot is a replacement for instructional design. It was one study in one game-based setting with one arrangement of supports. The useful conclusion is narrower: structured video scaffolding showed strong value in this context, and the combination of supports affected cognitive load and inquiry behavior."),
('host', "Now move from the game's hints to the teacher's work. What makes support fit the learning activity rather than merely decorate it?"),
('guest', "The timing and purpose matter. A prompt that helps a learner complete a task can interrupt productive thinking, while feedback that arrives too late may not support revision. The teacher's role is not eliminated by the game. The game changes what the teacher can notice and what the teacher must orchestrate."),
('host', "Which brings us to game-based structural debriefing, or GBSD. The name sounds like a bridge built out of arrows."),
('guest', "It is a framework for using video games to teach systems thinking. The authors integrate system-dynamics visualization tools with debriefing activities so that systems thinking becomes an explicit goal of gameplay and reflection. Their design-based research included a focus-group interview, three design workshops, iterative curriculum development, and implementation by three teachers in a middle-school life-science ecosystem unit."),
('host', "The game is not left alone to explain the ecosystem. The class talks it back into existence."),
('guest', "Beautifully put. GBSD uses debriefing to connect what happened in the game to concepts and relationships beyond it. The implementations supported flexibility: teachers created additional materials to address their classrooms' needs and the limits of the available game. That is evidence about a framework and a curriculum-design process, not a universal effect size for every game."),
('host', "So transfer needs a handrail."),
('guest', "Often more than one. A learner may master a game system without recognizing the underlying scientific system. Debriefing can make the relationship explicit: what variables changed, what feedback loop appeared, what assumption failed, and where the pattern might apply outside the game."),
('host', "Let's bring in a volume on learning, education, and games. What does it add to the teacher's work?"),
('guest', "It offers cases showing that a game's educational potential often depends on the surrounding curriculum. A game can provide a rich narrative or ethical problem, but instructors may need readings, structured discussion, and explicit attention to sensitive themes. Learning outcomes should be mapped around a game's affordances and limits, not assumed from its subject matter."),
('host', "So the game is an invitation, not a complete lesson plan."),
('guest', "Often. Pair or group play may create productive conversation, but it can also derail without facilitation. A narrative interface may offer agency while controlling the order in which information becomes available. Those design facts become learning opportunities when teachers make them discussable."),
('host', "Let's imagine a teacher receiving a report: ‘Your students explored the ecosystem game for twenty minutes.’ What should the report say next?"),
('guest', "It should say what was observed, what was inferred, and what remains unknown. Observed: students changed variables, revisited a model, or made a particular sequence of choices. Inferred: those patterns may indicate attention to relationships or difficulty with a concept, depending on the validated model. Unknown: whether students can explain the mechanism, transfer it to a new case, or collaborate well without the game's prompts."),
('host', "And the teacher asks the learners."),
('guest', "Yes. Ask players to explain decisions, compare strategies, identify evidence, and connect the game to the curriculum. A debrief is not a ceremonial chat after the real learning. It can be the moment the game becomes knowledge rather than merely experience."),
('host', "What are the design traps?"),
('guest', "First, decorative scaffolding: hints that sound educational but do not change the relevant activity. Second, assistance overload: too many prompts that fragment inquiry. Third, feedback without a process: telling someone they are wrong without helping them understand why. Fourth, narrative confusion: story details that consume working memory without supporting the learning goal. Fifth, assessment by proxy: treating time, points, or clicks as knowledge without validation."),
('host', "Sixth, believing the teacher has been replaced by a very enthusiastic tutorial voice."),
('guest', "The tutorial voice may be enthusiastic, but it cannot know the classroom's history, the learner's question behind the question, or the cultural meaning of a mistake unless the system is given far more context than most systems possess. Teachers can adapt materials, notice patterns, and help learners articulate transfer. The studies here repeatedly point toward design with teachers, not automation around them."),
('host', "Give us the practical recipe, Rowan."),
('guest', "Start with the learning goal and the evidence you would accept outside the game. Build mechanics, supports, and feedback around that goal. Test whether scaffolds reduce irrelevant load without breaking productive inquiry. Coordinate supports across individual action and collaborative talk. Plan debriefing and transfer before deployment. And evaluate AI support as one design element, not as a magic ingredient."),
('host', "The short version?"),
('guest', "A good learning game does not shout the lesson louder. It makes the lesson possible, then gives learners and teachers ways to see, question, and extend it."),
('host', "This was a dramatized synthesis of three sources, with a fictional correspondent, no fabricated author statements, and limitations in the show notes. Rowan, thank you."),
('guest', "Thank you. May your next hint arrive at the right time and contain fewer words than this sentence."),
('host', "Until next time: play carefully, debrief generously, and keep the human in the loop."),
]},
"004": {
"title": "The Feeling Learner and the Evidence Trail",
"slug": "the-feeling-learner-and-the-evidence-trail",
"dialogue": [
('host', "Welcome to Human in the Loop, where we ask whether the player, the learner, and the data point are actually the same person. Today's episode is about emotion, affective design, serious games, and formative evidence. Doctor Rowan Field is our fictional research correspondent. Rowan, are feelings allowed in the methods section?"),
('guest', "They are already there, often hiding in plain sight. And I am fictional: a composite voice translating research, not an author, not an interviewee, and not a ventriloquist dummy for anyone's conclusions. Everything today is paraphrased, and the limits matter."),
('host', "Excellent. My first feeling is methodological caution."),
('guest', "A healthy feeling. The taxonomy paper on learner-player emotions in serious games begins from a simple but consequential point: in serious games, emotions related to learning and emotions related to game elements can coexist. A player can feel curious about a science problem, frustrated by a game mechanic, proud of a strategy, or anxious about evaluation. These are not interchangeable signals."),
('host', "So if a player is delighted, we should not immediately write ‘learning occurred’ in the margin."),
('guest', "Correct. Delight might support attention, or it might come from an entertaining detour. Frustration might signal cognitive engagement, or it might signal a confusing interface. The taxonomy discusses affective games, affective learning, and the prospect of adaptive systems that recognize or respond to emotion. But recognizing an expression or a pattern is not the same as understanding its meaning."),
('host', "A raised eyebrow is not a standardized test."),
('guest', "Nor is a rapid sequence of retries. Context supplies the missing verbs. The learner may be testing a hypothesis, stuck on a control, enjoying a challenge, or trying to finish before the bus arrives. Any emotion-aware system needs a theory of what it is inferring and an opportunity for the learner to correct it."),
('host', "The emotional-design paper offers a framework rather than a single experiment, yes?"),
('guest', "It proposes connecting game design, emotion, cognition, and pedagogy through the Integrative Model of Emotion in Game-Based Learning, or EmoGBL. The aim is to help designers and educators reason about how game elements can interact with emotional and cognitive processes. The paper argues that affect and cognition are intertwined, and that design patterns could make those relationships more actionable."),
('host', "Design patterns: recipes for feelings?"),
('guest', "More like prompts for disciplined design. A pattern might ask what a mechanic invites the learner to feel, what cognitive activity accompanies that feeling, and whether the educational goal is supported. It should not promise that a particular color, reward, or story beat produces one universal emotion. Learners bring prior experience, identity, expectations, and context."),
('host', "So an emotional design pattern without a learner model is just a mood board with citations."),
('guest', "A stylish mood board, perhaps, but yes: insufficient. The paper is conceptual and design-oriented. Its value is in integrating perspectives and identifying a gap between knowing that emotions matter and knowing how specific game elements interact with learners in specific contexts. It does not validate every proposed pattern as an intervention."),
('host', "Let's make the learner-player distinction practical. What should a designer log?"),
('guest', "Log actions that are relevant to the learning and game systems, but avoid collecting intimate signals merely because they are technically available. If emotion is part of the research question, specify whether it is self-reported, behaviorally inferred, physiologically measured, or recognized by a model. Each source has a different error profile. Then design moments for reflection: ask the learner what they felt and why, rather than treating the model's guess as final."),
('host', "And privacy joins the party, wearing a nametag that says ‘please do not infer my soul from my mouse speed.’"),
('guest', "A very good nametag. Emotion data can be sensitive. Consent, purpose limitation, data minimization, and clear explanations are educational design requirements, not paperwork afterthoughts. Adaptive systems also need a graceful failure mode: if the system guesses wrong, it should offer a choice, not quietly steer a learner into a remedial tunnel."),
('host', "Now bring in the educational AR-game study about narrative and feedback."),
('guest', "That laboratory study involved 123 participants and investigated narrative and process-oriented feedback in relation to cognitive load and learning. Narrative and process-oriented feedback did not show a significant relationship with each other on cognitive load and learning. Process-oriented feedback improved transfer. Immersion was mediated by germane cognitive load, and both extraneous and germane cognitive load were related to recall."),
('host', "In other words, a story can pull us in, but the useful question is what the feedback helps us do with the experience."),
('guest', "Yes. Process-oriented feedback can connect an action to a mechanism or strategy. That is different from a reward chime or a red X. The study also cautions against collapsing immersion, enjoyment, load, recall, and transfer into a single outcome called engagement. These are related constructs, not synonyms."),
('host', "I would like to ban the phrase ‘engaged learners’ unless the speaker names which evidence they mean."),
('guest', "That would create some quiet conferences, but improve many abstracts. Engagement can refer to behavior, emotion, cognition, or social participation. A game may produce visible persistence while a learner's conceptual understanding remains shallow. Conversely, a learner may pause, talk, and appear less active while building a better model."),
('host', "The book Playful Testing makes the evidence trail explicit."),
('guest', "It describes formative assessment as collecting evidence to support conclusions about what learners know or can do. In a well-integrated learning game, mechanics can embody features of a learning goal, so playing well involves understanding a meaningful system. Embedded or stealth assessment can reduce interruption, but it does not remove the obligation to specify the inference."),
('host', "What is the inference chain?"),
('guest', "Something like this: the learner encounters a task; their action provides observable evidence; a model interprets that evidence in relation to a construct; an educator or system uses the interpretation for a decision. Every arrow can fail. The task may not elicit the construct. The action may have multiple explanations. The model may be miscalibrated. The decision may exceed the evidence."),
('host', "And emotion can influence every arrow."),
('guest', "Exactly. Anxiety can change how someone approaches a task. Curiosity can lead to productive exploration. Frustration can either support persistence or drive disengagement. But we should not use emotion as a hidden correction factor that explains away inconvenient data. If affect matters, measure it transparently and test the proposed relationship."),
('host', "Now bring the evidence trail to theory. What happens when a design experiment introduces a new construct?"),
('host', "And where does design-experiment theory fit into this episode?"),
('guest', "The paper on ontological innovation and theory in design experiments offers a methodological reminder. Design research can generate new ways of describing a phenomenon, but the work must make its theoretical moves visible. When a game-based learning study introduces a new construct—say, a particular form of affective participation—it should explain what changed in the ontology, how the construct is evidenced, and how readers can compare it with related ideas."),
('host', "That sounds like a plea against inventing a new noun every time a familiar learning behavior puts on a game costume."),
('guest', "A gentle plea, yes. New concepts can be valuable when they sharpen a real distinction. They become expensive when they obscure existing evidence or make comparison impossible. Theory helps designers decide which observations matter; evidence helps constrain the theory."),
('host', "Let's put the five sources on a design table. What questions should a team ask before adding emotional adaptation to a serious game?"),
('guest', "First: which learning process is the design supporting—recall, transfer, explanation, collaboration, or something else? Second: which game element is expected to influence which emotion or cognitive process? Third: how will the team know? Fourth: what alternative explanation could produce the same trace? Fifth: what happens when the system is wrong? Sixth: can the learner understand and contest the adaptation?"),
('host', "Seventh: did a real teacher or learner help shape the design?"),
('guest', "Yes. Eighth: is the surrounding activity prepared? A debrief, a reflection prompt, or a peer discussion may be the bridge from feeling to understanding. Ninth: are the outcomes proportionate to the evidence? A tentative signal can support a suggestion for reflection; it should not silently determine a high-stakes judgment."),
('host', "Can we make this playful without making it fluffy?"),
('guest', "Certainly. Playfulness is not the absence of rigor. A designer can invite wonder, surprise, humor, or challenge while specifying the learning target and checking the evidence. In fact, a playful system can make its assumptions visible through experimentation: what if the player chooses differently, what if the feedback is delayed, what if the group explains its reasoning?"),
('host', "What is the biggest misconception about emotion in game-based learning?"),
('guest', "That positive emotion is always good and negative emotion is always bad. Learning can involve uncertainty, effort, surprise, and temporary frustration. The design question is whether the emotion is productive, supported, and connected to the learner's goals. A system should not manufacture distress and call it rigor, nor remove every challenge and call it care."),
('host', "And the biggest misconception about assessment?"),
('guest', "That invisible assessment is automatically fairer, or that visible assessment is automatically worse. Fairness depends on validity, transparency, opportunity, consequences, and the learner's ability to understand what is happening. A quiet data trail can still make a loud decision."),
('host', "Give us the refrigerator magnet."),
('guest', "Feelings are evidence about an experience, not proof of learning. Game actions are evidence for an inference, not the inference itself. And every adaptation should leave a trail that a human can inspect and a learner can question."),
('host', "This episode was a dramatized synthesis of five research and design works. The correspondent is fictional, no author statements were fabricated, and the show notes link every source and identify limitations. Rowan, thank you."),
('guest', "Thank you. May your next affective model ask the learner a question before it answers one."),
('host', "Until next time: play with feeling, assess with humility, and keep the human in the loop."),
]}}

async def render(num, ep):
    outdir = ROOT / "episodes" / num
    parts = outdir / ("parts-v2" if num == "002" else "parts")
    parts.mkdir(parents=True, exist_ok=True)
    files=[]
    for i,(role,text) in enumerate(ep['dialogue']):
        p=parts/f"{i:03d}-{role}.mp3"
        if not p.exists() or p.stat().st_size < 1000:
            for attempt in range(4):
                try:
                    await edge_tts.Communicate(text, VOICE[role], rate="-3%" if role=='host' else "-5%").save(str(p))
                    break
                except Exception:
                    if attempt == 3: raise
                    await asyncio.sleep(2 + attempt)
        files.append(p)
    concat=outdir/'concat.txt'; concat.write_text(''.join(f"file '{p.as_posix()}'\n" for p in files))
    output=outdir/f"{ep['slug']}.mp3"
    ff=imageio_ffmpeg.get_ffmpeg_exe()
    subprocess.run([ff,'-y','-f','concat','-safe','0','-i',str(concat),'-c:a','libmp3lame','-b:a','128k',str(output)],check=True)
    print(num, output, len(' '.join(t for _,t in ep['dialogue']).split()))

async def main():
    for num,ep in EPISODES.items(): await render(num,ep)

if __name__=='__main__': asyncio.run(main())
